/**
 * Fully-populated example used by tests and the local demo seed.
 * These are illustrative numbers for exercising the math — NOT market data.
 */
import { emptyInputs } from './fields'
import type { DealInputs } from './types'

export function sampleInputs(overrides: Partial<DealInputs> = {}): DealInputs {
  return {
    ...emptyInputs(),
    address: '123 Example St',
    city: 'Exampleville',
    state: 'OH',
    zip: '44100',
    market: 'Example Market',
    propertyType: 'SFR',
    beds: 3,
    baths: 1.5,
    sqft: 1400,
    yearBuilt: 1955,
    purchasePrice: 100_000,
    closingCostPct: 0.03,
    closingCostAmount: null,
    inspectionCost: 500,
    attorneyCost: 1_000,
    titleCost: 1_500,
    otherAcquisitionCost: 0,
    projectMonths: 6,
    holdingCosts: 2_400,
    otherProjectCosts: 0,
    additionalEquity: 0,
    rehabEstimate: 40_000,
    rehabContingencyPct: 0.1,
    rehabDurationMonths: 4,
    rehabComplexity: 'Medium',
    acqLoanType: 'Hard money',
    acqLtv: 0.8,
    acqInterestRate: 0.12,
    acqPointsPct: 0.02,
    acqLoanFees: 1_000,
    acqTermYears: 1,
    acqInterestOnly: true,
    refiType: 'DSCR',
    refiLtv: 0.75,
    refiInterestRate: 0.07,
    refiTermYears: 30,
    refiClosingCostPct: 0.02,
    refiOtherCosts: 0,
    refiSeasoningMonths: 6,
    refiMinDscr: 1.0,
    arvConservative: 185_000,
    arvBase: 200_000,
    arvUpside: 215_000,
    compCount: 5,
    arvConfidence: 'High',
    marketRent: 1_800,
    conservativeRent: 1_650,
    upsideRent: 1_900,
    vacancyPct: 0.08,
    managementPct: 0.1,
    taxesAnnual: 2_400,
    insuranceAnnual: 1_200,
    hoaAnnual: 0,
    utilitiesAnnual: 0,
    maintenancePct: 0.05,
    capexPct: 0.05,
    otherOpexAnnual: 0,
    sellingCostPct: 0.06,
    targetAllInPct: 0.7,
    gateNoCredibleArv: 'no',
    gateTitleIssue: 'no',
    gateUninsurable: 'no',
    gateStructuralUnknownCost: 'no',
    gateAppreciationOnly: 'no',
    gateRehabNotEstimable: 'no',
    ...overrides,
  }
}
